# Generated by Django 5.1.5 on 2025-02-03 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0002_passwordentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordentry',
            name='password',
            field=models.TextField(),
        ),
    ]
