# Generated by Django 5.1.5 on 2025-02-03 20:04

import pyotp
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0003_alter_passwordentry_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='otp_secret',
            field=models.CharField(default=pyotp.random_base32, max_length=32),
        ),
    ]
