# Generated by Django 5.1.5 on 2025-02-09 08:26

import django.db.models.deletion
import pyotp
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0006_userprofile_otp_attempts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='passwordentry',
            name='password',
            field=models.TextField(verbose_name='Зашифрованный пароль'),
        ),
        migrations.AlterField(
            model_name='passwordentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='passwordentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='passwordentry',
            name='username',
            field=models.CharField(max_length=255, verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='passwordentry',
            name='website',
            field=models.CharField(max_length=255, verbose_name='Сайт'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_2fa_enabled',
            field=models.BooleanField(default=False, verbose_name='2FA включена'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='otp_attempts',
            field=models.IntegerField(default=0, verbose_name='Количество попыток ввода OTP'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='otp_locked_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Заблокирован до'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='otp_secret',
            field=models.CharField(default=pyotp.random_base32, max_length=32, verbose_name='Секретный ключ OTP'),
        ),
    ]
