# Generated by Django 5.1.5 on 2025-03-11 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0010_remove_userprofile_last_login_time_userloginhistory_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLoginHistory',
        ),
    ]
