# Generated by Django 5.1.5 on 2025-03-11 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0011_delete_userloginhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='failed_login_attempts',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_login_ip',
        ),
    ]
