# Generated by Django 5.1.5 on 2025-03-11 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0012_remove_userprofile_failed_login_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='failed_login_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='login_locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
