# Generated by Django 5.1.5 on 2025-03-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0014_rename_login_locked_until_userprofile_locked_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='otp_secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
