# Generated by Django 5.1.5 on 2025-03-18 06:52

import pyotp
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0015_alter_userprofile_otp_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='otp_secret',
            field=models.CharField(default=pyotp.random_base32, max_length=32),
        ),
    ]
