# Generated by Django 5.1.5 on 2025-03-18 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0016_alter_userprofile_otp_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='otp_secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
