# Generated by Django 5.1.5 on 2025-03-28 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0017_alter_userprofile_otp_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='master_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='master_locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
